name: "Setup env"
description: "Set up Python environment"

runs:
  using: composite
  steps:
    - name: Set up Python
      uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405
      with:
        python-version: 3.14
        architecture: x64

    - name: Install uv
      shell: bash
      run: pip install uv

    - name: Install just
      shell: bash
      run: |
        sudo apt update
        sudo apt install -y just

    - name: Install dependencies
      shell: bash
      run: just setup
