name: Formatting
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

  jobs:
    run-tests:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4

        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: 3.11
            architecture: x64

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install poetry
            poetry lock
            poetry install

        - name: Run linter
          run: | 
            poetry run flake8 src tests
            poetry run black --check src tests
            poetry run isort --check-only src tests

        - name: Run type check
          run: poetry run mypy src tests

        - name: Check for dead code
          run: poetry run vulture src tests --min-confidence 70
