name: Security
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

  jobs:
    get-runner:
      runs-on: ubuntu-latest
      outputs:
        runner: ${{ steps.get-runner.outputs.runner }}
      steps:
        - uses: actions/checkout@v4

        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: 3.11
            architecture: x64

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install poetry
            poetry lock
            poetry install

        - name: Run dependency security check
          run: |
            safety check --full-report -r requirements.txt
            bandit -r src tests
